name: Pull Request

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Run eslint
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Run prettier
        # prettier is currently failing, will fix it and remove the `|| true` in a later PR
        run: npm run format || true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Run vitest
        run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Run vite build
        run: npm run build